stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  image: alpine:latest
  script:
    - echo "Начинаем сборку проекта..."
    - echo "Сборка успешно завершена!"

test_job:
  stage: test
  image: alpine:latest
  script:
    - echo "Запуск unit-тестов..."
    - echo "Все тесты пройдены успешно (100%)"

deploy_job:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Развертывание приложения на сервере..."
    - echo "Деплой прошел успешно!"